@api = http://localhost:3000/api/activos1
@api3 = http://localhost:3000/api/activos
@api2 = http://localhost:3000/api/modelosz

@api4 = http://localhost:3000/api/activos/x

@api5 = http://localhost:3000/api/activosI



{{api4}}/1/18

###
PUT {{api3}}/3220
Content-Type: application/json

{   
    "EQC_serie":"55555",
    "EQC_placa":"55555",
    "EQC_EQUIP_id":2,
    "EQC_CLI_id":2,
    "EQC_USU_ing":17,
    "EQC_codTag":"S1001",
    "EQC_LOGO_id":2
}

###
http://localhost:3000/api/activos/VLTJ33CA

### add a product
POST https://api-seimalsa.herokuapp.com/api/activosI
Content-Type: application/json

{   
    "EQC_serie":"1235",
    "EQC_placa":"4321",
    "EQC_EQUIP_id":1,
    "EQC_CLI_id":1,
    "EQC_USU_ing":18,
    "EQC_codTag":"77777",
    "EQC_LOGO_id":1
}

### get product
{{api}}/4K7XCPRT

### delete product 
PUT  {{api}}/772

### delete product 
DELETE {{api}}/772

### get count
{{api3}}/count

### update
PUT {{api}}/767
Content-Type: application/json

{
    "name": "laptop",
    "description": "some laptop",
    "quantity": "20"
}

### get idCliente
{{api4}}/4


@api100 = http://localhost:3000/api/areaservicio/y

### get idCliente
{{api100}}/1


### get idCliente
@api200 = http://localhost:3000/api/tservicioPers
{{api200}}


### get idCliente
@api201 = http://localhost:3000/api/subcliente
{{api201}}

### add a product
POST http://localhost:3000/api/subclienteC
Content-Type: application/json

{
    "SC_nombre": "cjsa8",
   "SC_codUniversal": "cjsa007",
   "SC_direccion": "Tulipane7",
    "SC_establecimiento": "Los Tulipanes7",
   "SC_USU_ing": 18,
   "SC_identificacion": "091935434056",
   "SC_referencia": "Escuela Continente Americano5",
   "SC_tipoNegocio": "Desarrollo de Software5"
}


### add a product
PUT http://localhost:3000/api/requerimientos/3
Content-Type: application/json

{   
    "Ciudad":81,
    "Cliente":12,
    "Direccion": "AlboradaA",
    "Establecimiento":"Tiendas Don Guillermo",
    "FechaReq":"10/06/2024",
    "IVA":3,
    "Maps":"algo",
    "Modelo":2,
    "Observacion":"Fuga",
    "PersonaR":"Kevin Victores",
    "Placa":"H558889",
    "Serie":"P89625",
    "Servicio":1,
    "Subcliente":"Don Guillermo",
    "Subtotal":10,
    "TecnicoChofer":2,
    "Telefono":"09193543401",
    "TipoServicio":4,
    "Total":13,
    "details":[{
    }]
}


### add a product
POST http://localhost:3000/api/areaservicio
Content-Type: application/json

{   
    "AS_SS_id":1,
    "AS_USU_id":1,
    "AS_fecha":"25/06/2023",
     "AS_CLI_id":1,
    "AS_AT_id":1,
    "AS_OT_id":1,
    "AS_OT_codigo":"",
    "AS_TPS_id":1,
    "AS_EC_id":1,
    "AS_UBIC_id":1,
    "AS_serie":"123",
    "AS_placa":"456",
    "AS_EQUIP_id":1,
    "AS_LOGO_id":1,
    "AS_observacionTecnica":"cjsa",
    "AS_USU_ing":1,
    "AS_Subtotal":0,
    "AS_impuesto":0,
    "AS_iva":0,
    "AS_total":0,
    "AS_descCliente":0,
    "AS_descuento":0,
    "AS_descuentoR":0,
    "AS_descuentoS":0,
    "AS_descuentoP":0,
    "AS_fechaIngreso": "26/06/2023",
    "AS_EstadoFactura":0,
    "AS_Reporte":"cjsa",
    "AS_IE_id":0,
    "AS_ES_id":1,
    "AS_SEDE_id":1,
    "AS_fechaReq":"27/06/2023",
    "AS_semana":"",
    "AS_numReq":"",
    "AS_PR_id":1,
    "AS_UBIC_id2":1,
    "AS_TPSP_id":1,
    "AS_VEND_id":0,
    "AS_serie2":"123",
    "AS_placa2":"456",
    "AS_EQUIP_id2":1,
    "AS_LOGO_id2":1,
     "AS_observacion2":"cjsa",
      "AS_CT_idOrigen":0,
    "AS_serieCompresor":"cjsa"
}

### get idCliente

@api2010 = http://localhost:3000/api/detallesreq/3
{{api2010}}

### get idCliente

@api2011 = http://localhost:3000/api/resumen
{{api2011}}