@api = http://localhost:3000/api/activos1
@api3 = http://localhost:3000/api/activos
@api2 = http://localhost:3000/api/modelosz

@api4 = http://localhost:3000/api/activos/x

@api5 = http://localhost:3000/api/activosI



{{api4}}/1/18

###
PUT {{api3}}/3220
Content-Type: application/json

{   
    "EQC_serie":"55555",
    "EQC_placa":"55555",
    "EQC_EQUIP_id":2,
    "EQC_CLI_id":2,
    "EQC_USU_ing":17,
    "EQC_codTag":"S1001",
    "EQC_LOGO_id":2
}

###
http://localhost:3000/api/activos/VLTJ33CA

### add a product
POST https://api-seimalsa.herokuapp.com/api/activosI
Content-Type: application/json

{   
    "EQC_serie":"1235",
    "EQC_placa":"4321",
    "EQC_EQUIP_id":1,
    "EQC_CLI_id":1,
    "EQC_USU_ing":18,
    "EQC_codTag":"77777",
    "EQC_LOGO_id":1
}

### get product
{{api}}/4K7XCPRT

### delete product 
PUT  {{api}}/772

### delete product 
DELETE {{api}}/772

### get count
{{api3}}/count

### update
PUT {{api}}/767
Content-Type: application/json

{
    "name": "laptop",
    "description": "some laptop",
    "quantity": "20"
}

### get idCliente
{{api4}}/4


@api100 = http://localhost:3000/api/requerimientos/act/2

### get idCliente
{{api100}}


### get idCliente
@api200 = http://localhost:3000/api/requerimientos/act
{{api200}}/2


### get idCliente
@api201 = http://localhost:3000/api/subcliente
{{api201}}

### add a product
POST http://localhost:3000/api/usuarios/new
Content-Type: application/json

{
    "USU_nombre": "z",
   "USU_usuario": "z",
   "USU_clave":"123",
   "USU_cargo":"z",
   "USU_rol":"z"
}


### add a product
PUT http://localhost:3000/api/requerimientos/2
Content-Type: application/json

{   
    "Ciudad":81,
    "Cliente":12,
    "Direccion": "AlboradaA",
    "Establecimiento":"Tiendas Don Guillermo",
    "FechaReq":"10/06/2024",
    "IVA":null,
    "Maps":"algo",
    "Modelo":2,
    "Observacion":"Fuga",
    "PersonaR":"Kevin Victores",
    "Placa":"H558889",
    "Serie":"P89625",
    "Servicio":1,
    "Subcliente":"Don Guillermo",
    "Subtotal":null,
    "TecnicoChofer":2,
    "Telefono":"09193543401",
    "TipoServicio":4,
    "Total":null,
    "details":[{
    }]
}


### add a product
POST http://localhost:3000/api/areaservicio/new
Content-Type: application/json

{   
    "AS_secuencial": "CT5000",
    "AS_SS_id":1,
    "AS_USU_id":1,
    "AS_CLI_id":1,
    "AS_TPS_id":1,
    "AS_EC_id":1,
    "AS_UBIC_id":1,
    "AS_serie":"123",
    "AS_placa":"456",
    "AS_EQUIP_id":1,
    "AS_observacionTecnica":"cjsa",
    "AS_USU_ing":1,
    "AS_Subtotal":2.5,
    "AS_iva":1,
    "AS_total":3.5,
    "AS_fechaIngreso":"05-05-2024",
    "AS_Reporte":"2458",
    "AS_ES_id":1,
    "AS_fechaReq":"05-05-2024",
    "AS_EM_id":10,
    "AS_USU_edit":18,
    "AS_REQ_id":3
}

### get idCliente

@api2010 = http://localhost:3000/api/detallesreq/3
{{api2010}}

### get idCliente

@api2011 = http://localhost:3000/api/resumen
{{api2011}}